apiVersion: v1
kind: Service
metadata:
  name: db-app-deploy
  labels:
    name: db-app-deploy
    app: voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-app-deploy
    app: voting-app