apiVersion: v1
kind: Service
metadata:
  name: redis-app-deploy
  labels:
    name: redis-app-deploy
    app: voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-app-deploy
    app: voting-app