apiVersion: v1
kind: Service
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-deploy
    app: voting-app