apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-deploy
      app: voting-app
    
  template:
    metadata:
      name: result-app-deploy
      labels:
        name: result-app-deploy
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80    