apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-deploy
      app: voting-app
    
  template:
    metadata:
      name: worker-app-deploy
      labels:
        name: worker-app-deploy
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_worker